// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace src.Models;

public partial class Board
{
    public Guid Id { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public Guid UserId { get; set; }

    public Guid MountainId { get; set; }

    public int TourTime { get; set; }

    public int Difficulty { get; set; }

    public int MessageId { get; set; }

    public virtual ICollection<BoardChat> BoardChats { get; set; } = new List<BoardChat>();

    public virtual Mountain Mountain { get; set; }

    public virtual User User { get; set; }

    public virtual Message Message { get; set; }
}