// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace src.Models;

public partial class BoardChat
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public Guid BoardId { get; set; }

    public string Msg { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime Timestamp { get; set; }
    public bool IsSpam { get; set; }

    public double IsSpamConfidence { get; set; }

    public bool WasVerified { get; set; }

    public virtual Board Board { get; set; }

    public virtual User User { get; set; }
}