// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace src.Models;

public partial class Message
{
    public int Id { get; set; }

    public string Content { get; set; }

    /// <summary>
    /// Corresponds to is_spam_proc (BOOLEAN DEFAULT FALSE)
    /// Indicates if the background process has run on this message.
    /// </summary>
    public double IsSpamConf { get; set; }

    /// <summary>
    /// Corresponds to is_spam (NULL/TRUE/FALSE)
    /// The result of the spam check.
    /// </summary>
    public bool? IsSpam { get; set; }
}