// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace src.Models;

public partial class Mountain
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public int Height { get; set; }

    public int RegionId { get; set; }

    public string Nfc { get; set; }
    public decimal Lat { get; set; }
    public decimal Lon { get; set; }


    public virtual ICollection<Board> Boards { get; set; } = new List<Board>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Scan> Scans { get; set; } = new List<Scan>();
}