// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace src.Models;

public partial class PostComment
{
    public int Id { get; set; }

    public Guid CreatedBy { get; set; }

    public int PostId { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime Timestamp { get; set; }

    public string Message { get; set; }
    public bool IsSpam { get; set; }

    public double IsSpamConfidence { get; set; }

    public bool WasVerified { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Post Post { get; set; }
}