// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace src.Models;

public partial class Post
{
    public int Id { get; set; }

    public Guid CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime Timestamp { get; set; }

    public string Tagline { get; set; }

    public string StartMsg { get; set; }

    public Guid? MountainId { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Mountain Mountain { get; set; }

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();
}