// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace src.Models;

public partial class Scan
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public Guid MountainId { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime Timestamp { get; set; }

    public virtual Mountain Mountain { get; set; }

    public virtual User User { get; set; }
}