// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace src.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public virtual ICollection<BoardChat> BoardChats { get; set; } = new List<BoardChat>();

    public virtual ICollection<Board> Boards { get; set; } = new List<Board>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Scan> Scans { get; set; } = new List<Scan>();
}