name: .NET Core CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test with Coverage
      id: test_step
      continue-on-error: true 
      run: |
        dotnet test --no-build --configuration Release \
        --logger "trx;LogFileName=test-results.trx" \
        --collect:"XPlat Code Coverage" \
        --results-directory ./TestResults

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Test Results
        path: 'TestResults/*.trx'
        reporter: dotnet-trx

    - name: Generate Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'TestResults/**/*.cobertura.xml'
        badge: true
        fail_below_min: false 
        format: markdown
        output: both

    - name: Write Summary to Job
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      
    - name: Final Status Check
      if: steps.test_step.outcome == 'failure'
      run: |
        echo "::error::Tests failed. View the 'Test Results' tab for details."
        exit 1